LibraryWeb/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibraryWeb.Models
{
    public class Book : Product
    {
        public string Author { get; set; }
        public string Genre { get; set; }
        public Book( string name, string author, string genre, int count, string publisher, int year) : base(name, count, publisher, year)
        {
            Author = author;
            Genre = genre;
        }
        public Book() : base()
        {
            Author = "";
            Genre = "";
        }
        public bool CompareTo(Book other)
        {
            return Name == other.Name && Author == other.Author && Genre == other.Genre && Publisher == other.Publisher && Year == other.Year;
        }
    }
}

LibraryWeb/Models/ErrorViewModel.cs
using System;

namespace LibraryWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibraryWeb/Models/Journal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibraryWeb.Models
{
    public class Journal : Product
    {
        public int Periodically { get; set; }
        public int Number { get; set; }
        public Journal(string name, int count, string publisher, int year, int periodically, int number): base(name, count, publisher, year)
        {
            Periodically = periodically;
            Number = number;
        }
        public Journal() : base()
        {
            Periodically = 0;
            Number = 0;
        }
        public bool CompareTo(Journal other)
        {
            return Name == other.Name && Publisher == other.Publisher && Year == other.Year && Periodically == other.Periodically && Number == other.Number;
        }
    }
}

LibraryWeb/Models/LibraryContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryWeb.Models
{
    public class LibraryContext : DbContext
    {
        public DbSet<Book> Books { get; set; }
        public DbSet<Journal> Journals { get; set; }
        public LibraryContext(DbContextOptions<LibraryContext> options) : base(options)
        {
            Database.EnsureCreated();
        }
    }
}

LibraryWeb/Models/Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryWeb.Models
{
    public class Model
    {
        public List<Book> Books { get; set; }
        public List<Journal> Journals { get; set; }
        public Model()
        {
            Books = new List<Book>();
            Journals = new List<Journal>();
        }
    }
}

LibraryWeb/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibraryWeb.Models
{
    public class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public string Publisher { get; set; }
        public int Year { get;  set; }
        public Product( string name, int count, string publisher, int year)
        {
            Name = name;
            Count = count;
            Publisher = publisher;
            Year = year; 
        }
        public Product() : this("", 0, "", 0)
        {

        }
        public bool CompareTo(Product other)
        {
            return Name == other.Name;
        }
    }
}

LibraryWeb/Controllers/LibraryController.cs
using LibraryWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryWeb.Controllers
{
    public class LibraryController : Controller
    {
        LibraryContext dataBase;
        public LibraryController(LibraryContext context)
        {
            dataBase = context;
        }
        public IActionResult Index()
        {
            string name = "";
            ViewData["Name"] = name;
            return View();
        }
        public IActionResult PrintBooks()
        {
            ViewData["Books"] = dataBase.Books.ToList();
            return View();
        }
        public IActionResult PrintJournals()
        {
            ViewData["Journals"] = dataBase.Journals.ToList();
            return View();
        }
        public RedirectToActionResult AddBook(Book book)
        {
            addBook(book);
            dataBase.SaveChanges();
            return RedirectToAction("PrintBooks");
        }
        private void addBook(Book book)
        {
            foreach (Book element in dataBase.Books)
                if (element.CompareTo(book))
                {
                    element.Count += book.Count;
                    dataBase.Entry(element).State = EntityState.Modified;
                    return;
                }
            dataBase.Books.Add(book);
        }
        public RedirectToActionResult AddJournal(Journal journal)
        {
            addJournal(journal);
            dataBase.SaveChanges();
            return RedirectToAction("PrintJournals");
        }
        private void addJournal(Journal journal)
        {
            foreach (Journal element in dataBase.Journals)
                if (element.CompareTo(journal))
                {
                    element.Count += journal.Count;
                    dataBase.Entry(element).State = EntityState.Modified;
                    return;
                }
            dataBase.Journals.Add(journal);
        }
        public RedirectToActionResult EditBook(Book book)
        {
            editBook(book);
            dataBase.SaveChanges();
            return RedirectToAction("PrintBooks");
        }
        public RedirectToActionResult EditJournal(Journal journal)
        {
            editJournal(journal);
            dataBase.SaveChanges();
            return RedirectToAction("PrintJournals");
        }
        private void editJournal(Journal journal)
        {
            int index = journal.id;
            dataBase.Entry(journal).State = EntityState.Modified;
            foreach (Journal element in dataBase.Journals)
            {
                if (element.CompareTo(journal) && index != element.id)
                {
                    element.Count += journal.Count;
                    dataBase.Entry(element).State = EntityState.Modified;
                    dataBase.Journals.Remove(journal);
                    return;
                }
            }
        }
        private void editBook(Book book)
        {
            int index = book.id;
            dataBase.Entry(book).State = EntityState.Modified;
            foreach(Book element in dataBase.Books)
            {
                if (element.CompareTo(book) && index != element.id)
                {
                    element.Count += book.Count;
                    dataBase.Entry(element).State = EntityState.Modified;
                    dataBase.Books.Remove(book);
                    return;
                }
            }
        }
        public RedirectToActionResult DeleteBook(Book book)
        {
            dataBase.Books.Remove(book);
            dataBase.SaveChanges();
            return RedirectToAction("PrintBooks");
        }
        public RedirectToActionResult DeleteJoural(Journal journal)
        {
            dataBase.Journals.Remove(journal);
            dataBase.SaveChanges();
            return RedirectToAction("PrintJournals");
        }
        public IActionResult AllSearch(string name)
        {
            Model model = new Model();
            foreach (Book element in dataBase.Books)
                if (element.CompareTo(new Product { Name = name }))
                    model.Books.Add(element);
            foreach (Journal element in dataBase.Journals)
                if (element.CompareTo(new Product { Name = name }))
                    model.Journals.Add(element);
            return View(model);
        }
        public IActionResult SearchBooks(string name)
        {
            List<Book> books = new List<Book>();
            foreach (Book element in dataBase.Books)
                if (element.CompareTo(new Product { Name = name }))
                    books.Add(element);
            return View(books);
        }
        public IActionResult SearchJournals(string name)
        {
            List<Journal> journals = new List<Journal>();
            foreach (Journal element in dataBase.Journals)
                if (element.CompareTo(new Product { Name = name }))
                    journals.Add(element);
            return View(journals);
        }
    }
}

LibraryWeb/Views/Library/AllSearch.cshtml
@model LibraryWeb.Models.Model
@{
    ViewData["Title"] = "Поиск";
    Layout = "_Layout";
}
<header>
    <nav class="navbar border">
        <div class="container-menu">
            <div class="brand"><a class="navbar-brand" asp-controller="Library" asp-action="Index">LibraryWeb</a></div>
            <div class="menu">
                <div class="point-menu-1"><a class="point-menu" asp-controller="Library" asp-action="PrintBooks">Книги</a></div>
                <div class="point-menu-2"><a class="point-menu" asp-controller="Library" asp-action="PrintJournals">Журналы</a></div>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <table>

            @{
                if (Model.Books.Count() == 0 && Model.Journals.Count() == 0)
                {
                    <div>По данному запросу ничего не найдено</div>
                }
                else if (Model.Books.Count() != 0)
                {
                    <tr>
                        <td>Название</td>
                        <td>Издательство</td>
                        <td>Периодичность</td>
                        <td>Номер</td>
                        <td>Количество</td>
                        <td>Год</td>
                    </tr>
                    foreach (Book element in Model.Books)
                    {
                        <form>
                        <tr>
                            <td>
                                <input type="text" readonly value="@element.Name" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Author" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Genre" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Publisher" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Count" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Year" />
                            </td>
                        </tr>
                        </form>
                    }
                }
                else if (Model.Journals.Count() != 0)
                {
                    <tr>
                        <td>Название</td>
                        <td>Издательство</td>
                        <td>Периодичность</td>
                        <td>Номер</td>
                        <td>Количество</td>
                        <td>Год</td>
                    </tr>
                    foreach (Journal element in Model.Journals)
                    {
                        <form>
                        <tr>
                            <td>
                                <input type="text" readonly value="@element.Name" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Publisher" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Periodically" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Number" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Count" />
                            </td>
                            <td>
                                <input type="text" readonly value="@element.Year" />
                            </td>
                        </tr>
                        </form>
                    }
                }
            }
            <tr>
        </table>
    </main>
</div>

LibraryWeb/Views/Library/Index.cshtml
@model LibraryWeb.Models.Book
@{
    ViewData["Title"] = "Главная";
    Layout = "_Layout";
}
<header>
<nav class="navbar border">
    <div class="container-menu">
        <div class="brand"><a class="navbar-brand" asp-controller="Library" asp-action="Index">LibraryWeb</a></div>
        <div class="menu">
            <div class="point-menu-1"><a class="point-menu" asp-controller="Library" asp-action="PrintBooks">Книги</a></div>
            <div class="point-menu-2"><a class="point-menu" asp-controller="Library" asp-action="PrintJournals">Журналы</a></div>
        </div>
        <form asp-action="AllSearch" asp-controller="Library">
            <div class="input-group">
                <div class="form-outline">
                    <input type="search" id="form1" asp-for="Name" class="form-control" />
                </div>
                <button type="submit" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                    </svg>
                </button>
            </div>
        </form>
    </div>
</nav>
</header>
    <div class="container">
        <main role="main">
            <div class="image-1">
                <a asp-controller="Library" asp-action="PrintBooks">
                    <svg xmlns="http://www.w3.org/2000/svg" width="15em" height="15em" fill="currentColor" class="bi bi-journal-bookmark" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M6 8V1h1v6.117L8.743 6.07a.5.5 0 0 1 .514 0L11 7.117V1h1v7a.5.5 0 0 1-.757.429L9 7.083 6.757 8.43A.5.5 0 0 1 6 8z" />
                        <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
                        <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
                    </svg>
                </a>
            </div>
            <div class="image-2">
                <a asp-controller="Library" asp-action="PrintJournals">
                    <svg xmlns="http://www.w3.org/2000/svg" width="15em" height="15em" fill="currentColor" class="bi bi-journal" viewBox="0 0 16 16">
                        <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
                        <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
                    </svg>
                </a>
            </div>
        </main>
    </div>

LibraryWeb/Views/Library/PrintBooks.cshtml
@model LibraryWeb.Models.Book
@{
    ViewData["Title"] = "Список книг";
    Layout = "_Layout";
}
<header>
    <nav class="navbar border">
        <div class="container-menu">
            <div class="brand"><a class="navbar-brand" asp-controller="Library" asp-action="Index">LibraryWeb</a></div>
            <div class="menu">
                <div class="point-menu-1"><a class="point-menu" asp-controller="Library" asp-action="PrintBooks">Книги</a></div>
                <div class="point-menu-2"><a class="point-menu" asp-controller="Library" asp-action="PrintJournals">Журналы</a></div>
            </div>
            <form asp-action="AllSearch" asp-controller="Library">
                <div class="input-group">
                    <div class="form-outline">
                        <input type="search" id="form1" asp-for="Name" class="form-control" />
                    </div>
                    <button type="submit" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <table>
            <tr>
                <td></td>
                <td>Название</td>
                <td>Автор</td>
                <td>Жанр</td>
                <td>Издательство</td>
                <td>Количество</td>
                <td>Год</td>
                <td></td>
            </tr>
            @foreach (Book element in (List<Book>)ViewData["Books"])
            {
                int i = 1;
                <form id="@element.id" asp-action="EditBook" asp-route-id="@element.id" method="post">
                <tr>
                    <td>
                        <input type="button" onClick="clickButton(@element.id)" value="🖊" />
                    </td>
                    <td>
                        <input type="text" asp-for="Name" readonly value="@element.Name" />
                    </td>
                    <td>
                        <input type="text" asp-for="Author" readonly value="@element.Author" />
                    </td>
                    <td>
                        <input type="text" asp-for="Genre" readonly value="@element.Genre" />
                    </td>
                    <td>
                        <input type="text" asp-for="Publisher" readonly value="@element.Publisher" />
                    </td>
                    <td>
                        <input type="text" asp-for="Count" readonly value="@element.Count" />
                    </td>
                    <td>
                        <input type="text" asp-for="Year" readonly value="@element.Year" />
                    </td>
                    <td><input type="submit" asp-controller="Library" asp-route-id="@element.id" asp-action="DeleteBook" value="Удалить" onclick="clickCancel(@element.id)" /></td>
                </tr>
                </form>
                i++;
            }
            <tr>
                <form asp-action="AddBook" method="post">
                <td></td>
                <td>
                    <input type="text" asp-for="Name" />
                </td>
                <td>
                    <input type="text" asp-for="Author" />
                </td>
                <td>
                    <input type="text" asp-for="Genre" />
                </td>
                <td>
                    <input type="text" asp-for="Publisher" />
                </td>
                <td>
                    <input type="text" asp-for="Count" />
                </td>
                <td>
                    <input type="text" asp-for="Year" />
                </td>
                <td>
                    <input type="submit" value="Добавить" />
                </td>
                </form>
            </tr>
        </table>
    </main>
</div>
    <script>
        var obj = { Name: "", Autor: "", Genre: "", Publisher: "", Count: 0, Year: 0 };
        var formaction;
        function clickButton(id) {
            let element = document.getElementById(id);
            obj.Name = element[1].value;
            obj.Autor = element[2].value;
            obj.Genre = element[3].value;
            obj.Publisher = element[4].value;
            obj.Count = element[5].value;
            obj.Year = element[6].value;
            let input = element[0];
            if (input.attributes[2].value === "🖊") {
                input.attributes[2].value = "✓";
                input.attributes[0].value = "button";
                for (let i = 1; i < 8; i++) {
                    element[i].readOnly = false;
                }
                element[7].value = "Отменить";
                formaction = element[7].attributes[2];
                element[7].removeAttribute("formaction");
                element[7].attributes[0].value = "button";
            }
            else {
                input.attributes[2].value = "🖊";
                input.attributes[0].value = "submit";
                for (let i = 1; i < 8; i++) {
                    element[i].readOnly = true;
                }
                element[7].value = "Удалить";
                element.setAttribute("formaction", formaction);
                element[7].attributes[0].value = "submit";
            }
        }
        function clickCancel(id) {
            let element = document.getElementById(id);
            let input = element[7];
            if (input.attributes[1].value === "Отменить") {
                input.attributes[2].value = "🖊";
                input.attributes[0].value = "submit";
                for (let i = 1; i < 8; i++) {
                    element[i].readOnly = true;
                }
                element[7].value = "Удалить";
                element.setAttribute("formaction", formaction);
                element[7].attributes[0].value = "submit";
                element[1].value = obj.Name;
                element[2].value = obj.Autor;
                element[3].value = obj.Genre;
                element[4].value = obj.Publisher;
                element[5].value = obj.Count;
                element[6].value = obj.Year;
            }
        }
    </script>

LibraryWeb/Views/Library/PrintJournals.cshtml
@model LibraryWeb.Models.Journal
@{
    ViewData["Title"] = "Список журналов";
    Layout = "_Layout";
}
<header>
    <nav class="navbar border">
        <div class="container-menu">
            <div class="brand"><a class="navbar-brand" asp-controller="Library" asp-action="Index">LibraryWeb</a></div>
            <div class="menu">
                <div class="point-menu-1"><a class="point-menu" asp-controller="Library" asp-action="PrintBooks">Книги</a></div>
                <div class="point-menu-2"><a class="point-menu" asp-controller="Library" asp-action="PrintJournals">Журналы</a></div>
            </div>
            <form asp-action="AllSearch" asp-controller="Library">
                <div class="input-group">
                    <div class="form-outline">
                        <input type="search" id="form1" asp-for="Name" class="form-control" />
                    </div>
                    <button type="submit" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <table>
            <tr>
                <td></td>
                <td>Название</td>
                <td>Издательство</td>
                <td>Периодичность</td>
                <td>Номер</td>
                <td>Количество</td>
                <td>Год</td>
                <td></td>
            </tr>
            @foreach (Journal element in (List<Journal>)ViewData["Journals"])
            {
                <form id="@element.id" asp-route-id="@element.id" asp-action="EditJournal" method="post">
                <tr>
                    <td>
                        <input type="button" onClick="clickButton(@element.id)" value="🖊" />
                    </td>
                    <td>
                        <input type="text" asp-for="Name" readonly value="@element.Name" />
                    </td>
                    <td>
                        <input type="text" asp-for="Publisher" readonly value="@element.Publisher" />
                    </td>
                    <td>
                        <input type="text" asp-for="Periodically" readonly value="@element.Periodically" />
                    </td>
                    <td>
                        <input type="text" asp-for="Number" readonly value="@element.Number" />
                    </td>
                    <td>
                        <input type="text" asp-for="Count" readonly value="@element.Count" />
                    </td>
                    <td>
                        <input type="text" asp-for="Year" readonly value="@element.Year" />
                    </td>
                    <td><input type="submit" asp-controller="Library" asp-route-id="@element.id" asp-action="DeleteJoural" value="Удалить" onclick="clickCancel(@element.id)" /></td>
                </tr>
                </form>
            }
            <tr>
                <form asp-action="AddJournal" method="post">
                <td></td>
                <td>
                    <input type="text" asp-for="Name" />
                </td>
                <td>
                    <input type="text" asp-for="Publisher" />
                </td>
                <td>
                    <input type="text" asp-for="Periodically" />
                </td>
                <td>
                    <input type="text" asp-for="Number" />
                </td>
                <td>
                    <input type="text" asp-for="Count" />
                </td>
                <td>
                    <input type="text" asp-for="Year" />
                </td>
                <td>
                    <input type="submit" value="Добавить" />
                </td>
                </form>
            </tr>
        </table>
    </main>
</div>
        <script>
            var obj = { Name: "", Publisher: "", Periodically: 0, Number: 0, Count: 0, Year: 0 };
            var formaction;
            function clickButton(id) {
                let element = document.getElementById(id);
                obj.Name = element[1].value;
                obj.Publisher = element[2].value;
                obj.Periodically = element[3].value;
                obj.Number = element[4].value;
                obj.Count = element[5].value;
                obj.Year = element[6].value;
                let input = element[0];
                if (input.attributes[2].value === "🖊") {
                    input.attributes[2].value = "✓";
                    input.attributes[0].value = "button";
                    for (let i = 1; i < 8; i++) {
                        element[i].readOnly = false;
                    }
                    element[7].value = "Отменить";
                    formaction = element[7].attributes[2];
                    element[7].removeAttribute("formaction");
                    element[7].attributes[0].value = "button";
                }
                else {
                    input.attributes[2].value = "🖊";
                    input.attributes[0].value = "submit";
                    for (let i = 1; i < 8; i++) {
                        element[i].readOnly = true;
                    }
                    element[7].value = "Удалить";
                    element.setAttribute("formaction", formaction);
                    element[7].attributes[0].value = "submit";
                }
            }
            function clickCancel(id) {
                let element = document.getElementById(id);
                let input = element[7];
                if (input.attributes[1].value === "Отменить") {
                    input.attributes[2].value = "🖊";
                    input.attributes[0].value = "submit";
                    for (let i = 1; i < 8; i++) {
                        element[i].readOnly = true;
                    }
                    element[7].value = "Удалить";
                    element.setAttribute("formaction", formaction);
                    element[7].attributes[0].value = "submit";
                    element[1].value = obj.Name;
                    element[2].value = obj.Publisher;
                    element[3].value = obj.Periodically;
                    element[4].value = obj.Number;
                    element[5].value = obj.Count;
                    element[6].value = obj.Year;
                }
            }
        </script>

LibraryWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @RenderBody()

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LibraryWeb - <a asp-area="" asp-controller="Library" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>